name = "GeoInterface"
uuid = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
authors = ["JuliaGeo and contributors"]
version = "1.0.1"

[deps]
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
Extents = "0.1"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GeoFormatTypes", "Documenter"]
