name = "GeoInterface"
uuid = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
authors = ["JuliaGeo and contributors"]
version = "1.6.1"

[deps]
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"

[weakdeps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"

[extensions]
GeoInterfaceRecipesBaseExt = "RecipesBase"
GeoInterfaceMakieExt = ["Makie", "GeometryBasics"]

[compat]
DataAPI = "1"
CairoMakie = "0.15"
Extents = "0.1.1"
GeoFormatTypes = "0.4"
GeometryBasics = "0.5"
Makie = "0.23, 0.24"
RecipesBase = "1"
julia = "1.10"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CairoMakie", "Documenter", "GeoFormatTypes", "Makie", "Plots", "Test"]
