name = "GeoInterface"
uuid = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
authors = ["JuliaGeo and contributors"]
version = "1.2.1"

[deps]
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"

[compat]
Extents = "0.1.1"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
