name = "GeoInterfaceMakie"
uuid = "0edc0954-3250-4c18-859d-ec71c1660c08"
authors = ["JuliaGeo and contributors"]
version = "0.1.3"

[deps]
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"

[compat]
GeoInterface = "1"
GeometryBasics = "0.4.4"
MakieCore = "0.5.1, 0.6"
julia = "1.6"

[extras]
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[targets]
test = ["Test", "LibGEOS", "Makie"]
