name = "GeoInterfaceMakie"
uuid = "0edc0954-3250-4c18-859d-ec71c1660c08"
authors = ["JuliaGeo and contributors"]
version = "0.1.9"

[deps]
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"

[weakdeps]
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"

[extensions]
GeoInterfaceMakieMakieCoreExt = ["MakieCore", "GeometryBasics"]

[compat]
GeoInterface = "1"
GeometryBasics = "0.4.4, 0.5"
MakieCore = "0.5.1, 0.6, 0.7.1, 0.8, 0.9"
julia = "1.6"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CairoMakie", "Makie", "LibGEOS"]
